<?php

namespace Tests;

use Core\Services\Template;
use PHPUnit\Framework\TestCase;

class TemplateTest extends TestCase {

    /**
     * @var Template
     */
    private $_service;

    protected function setUp() {
        $this->_service = Template::initWithArgs();
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @param string $name
     * @param string $expected
     * @dataProvider getTemplateFilenameByNameDataProvider
     */
    public function testGetTemplateFilenameByName($name, $expected) {
        $this->assertEquals($expected, $this->_service->getTemplateFilenameByName($name));
    }

    public function getTemplateFilenameByNameDataProvider() {
        return [
            ['Москва', '/home/serqol/workspace/hench/templates/1Москва Заключение.doc'],
            ['Казань', '/home/serqol/workspace/hench/templates/1Казань Заключение.doc'],
        ];
    }
}